version: "3.8"
services:

  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    command: start --log trace --user root --pass root memory
    ports:
      - 8000:8000
    networks:
      - my-garden

networks:
  my-garden:
    driver: bridge
